db:
 host: "20.224.50.155"
 port: "3306"
 user: "group01"
 password: "@Br1ghtsGr0up01!"
 database: "northwind01"
 
http:
 host: "localhost"
 port: "8081"
 
shipping.ext:
  host: "20.224.50.155"
  port: "8081"
 