#%RAML 1.0
title: offer-sys-api
types:
  Offer: !include data types/offer-data-type.raml

/offers:
  post:
    description: Create offer for client
    body:
      application/json:
        example: !include examples/offer-example.raml
    responses:
      201: 
        body: 
          application/json:
            example:
              message: "Offer is created succesfully"
     
  get:
    description: Get list of all  created offers
    responses:
        200:
          body:
            application/json:
              type: object
              example: !include examples/offer-examples.raml

  /{customerID}:
    get: 
      description: get a list of proposed offers by customer ID
      queryParameters:
          status:
            enum:
              - Proposed
      responses:
        200:
          body:
            application/json:
              type: Offer
              examples:
                output: !include examples/offer-example.raml
              
  patch:
    description: Salesperson updates offer as proposed
    body:
      application/json:
        type: Offer
        examples: !include examples/offer-example.raml
    responses:
      201:
        body:
          application/json:
            example:
              message: "Offer updated succesfully."